##############################################################################################
#
# This Workflow is responsible for triggering release candidate builds (iOS & Android).
# You need to provide the semantic version of the release and the release branch
# must exist on the repository
#
##############################################################################################
name: Create RC builds

on:
  workflow_dispatch:
    inputs:
      semver:
        description: 'release version'
        required: true
jobs:
  bump-version:
    uses: ./.github/workflows/update-latest-build-version.yml
    with:
      base-branch: release/${{ inputs.semver }}
    secrets:
      PR_TOKEN: ${{ secrets.PR_TOKEN }}
    permissions:
      id-token: write
      contents: write

  trigger-rc-build:
    runs-on: ubuntu-latest
    needs:
      - bump-version
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: release/${{ inputs.semver }}
      - name: Trigger RC Build
        env:
          SEMVER: ${{ inputs.semver }}
          GH_REF_NAME: release/${{ inputs.semver }}
          COMMIT_HASH: ${{ needs.bump-version.outputs.commit-hash }}
          BUILD_NUMBER: ${{ needs.bump-version.outputs.build-version }}
          BITRISE_APP_ID: ${{ secrets.BITRISE_APP_ID }}
          BITRISE_BUILD_TRIGGER_TOKEN: ${{ secrets.BITRISE_BUILD_TRIGGER_TOKEN }}
          BITRISE_API_TOKEN: ${{ secrets.BITRISE_API_TOKEN }}
        run: ./.github/scripts/rc-builds.sh
