##############################################################################################
#
# This Workflow is responsible for triggering release candidate builds (iOS & Android).
# You need to provide the semantic version of the release and the release branch
# must exists on the repository
#
##############################################################################################
name: Create RC builds

on:
  workflow_dispatch:
    inputs:
      semver:
        description: 'release version'
        required: true
jobs:
  generate-build-version:
    uses: MetaMask/metamask-mobile-build-version/.github/workflows/metamask-mobile-build-version.yml@v0.3.0
    permissions:
      id-token: write

  bump-version:
    runs-on: ubuntu-latest
    needs:
      - generate-build-version
    outputs:
      commit-hash: ${{ steps.bump-script.outputs.commit-hash }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: release/${{ inputs.semver }}
          token: ${{ secrets.PR_TOKEN }}
      - id: bump-script
        uses: ./.github/actions/bump-build-version
        with:
          build-version: ${{ needs.generate-build-version.outputs.build-version }}
          ref: release/${{ inputs.semver }}

  trigger-rc-build:
    runs-on: ubuntu-latest
    needs:
      - generate-build-version
      - bump-version
    steps:
      - name: Trigger RC Build
        env:
          SEMVER: ${{ inputs.semver }}
          GH_REF_NAME: release/${{ inputs.semver }}
          COMMIT_HASH: ${{ needs.bump-version.outputs.commit-hash }}
          BUILD_NUMBER: ${{ needs.generate-build-version.outputs.build-version }}
          BITRISE_APP_ID: ${{ secrets.BITRISE_APP_ID }}
          BITRISE_BUILD_TRIGGER_TOKEN: ${{ secrets.BITRISE_BUILD_TRIGGER_TOKEN }}
          BITRISE_API_TOKEN: ${{ secrets.BITRISE_API_TOKEN }}
        run: ./scripts/rc-builds.sh
