name: 'Check PR Max Lines'

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  pull-requests: write # Required for the called workflow to manage labels

jobs:
  check-pr-max-lines:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR lines changed
        uses: MetaMask/github-tools/.github/actions/pr-line-check@072c900e2447470ad7ad5d8a74c14f253d583d9f
        with:
          max-lines: '1000'
          ignore-patterns: '(\.lock|\.snap)$'
