name: Cherry Pick Commit

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Target branch name to merge the cherry-picked branch into'
        required: true
      commit_hash:
        description: 'Commit Hash'
        required: true
      PR_number:
        description: 'PR # Associated with Cherry Pick'
        required: true
jobs:
  cherry-pick:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout and setup high risk environment
        uses: MetaMask/action-checkout-and-setup@v1
        with:
          is-high-risk-environment: false
      - name: Create Cherry Pick PR
        id: create-cherry-pick-pr
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME:  ${{ github.event.inputs.branch_name }}
          COMMIT_HASH:  ${{ github.event.inputs.commit_hash }}
          PR_NUMBER:    ${{ github.event.inputs.PR_number }}
        run: |
          ./scripts/create-cherry-pick-pr.sh "$BRANCH_NAME" "$COMMIT_HASH" "$PR_NUMBER"
