name: Post Merge Validation

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  post-merge-validation-tracker:
    runs-on: ubuntu-latest
    steps:
      - name: Run post-merge validation
        uses: MetaMask/github-tools/.github/actions/post-merge-validation@072c900e2447470ad7ad5d8a74c14f253d583d9f
        with:
          repo: ${{ github.repository }}
          start-hour-utc: '7'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          google-application-creds-base64: ${{ secrets.GCP_RLS_SHEET_ACCOUNT_BASE64 }}
