##############################################################################################
#
# This Workflow is responsible for updating the latest build version of the project.
# You can provide your own base branch, tag, or SHA for git operations and the pull request.
# and it will generate the latest build version & update the neccessary files for you.
#
##############################################################################################
name: Create RC builds

on:
  push:
    branches:
      - "rc-builds-gh-workflow"
  workflow_dispatch:
    inputs:
      semver:
        description: 'release version'
        required: true
jobs:
  generate-build-version:
    uses: MetaMask/metamask-mobile-build-version/.github/workflows/metamask-mobile-build-version.yml@v0.3.0
    permissions:
      id-token: write

  bump-version-and-build-rc:
    runs-on: ubuntu-latest
    needs: generate-build-version
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ inputs.semver }}
          token: ${{ secrets.PR_TOKEN }}

      - name: Build RC
        env:
          SEMVER: $ {{ inputs.semver }}
          BUILD_NUMBER: ${{ needs.generate-build-version.outputs.build-version }}
          BITRISE_APP_ID: ${{ secrets.BITRISE_APP_ID }}
          BITRISE_BUILD_TRIGGER_TOKEN: ${{ secrets.BITRISE_BUILD_TRIGGER_TOKEN }}
          BITRISE_API_TOKEN: ${{ secrets.BITRISE_API_TOKEN }}
        run: ./rc-builds.sh
        working-directory: '.github/scripts'
