##############################################################################################
#
# This Workflow is responsible for updating the latest build version of the project.
# You can provide your own base branch, tag, or SHA for git operations and the pull request.
# and it will generate the latest build version & update the neccessary files for you.
#
##############################################################################################
name: Create RC builds

on:
  push:
    branches:
      - "rc-builds-gh-workflow"
  workflow_dispatch:
    inputs:
      semver:
        description: 'release version'
        required: true
jobs:
  bump-version-and-build-rc:
    runs-on: ubuntu-latest
    needs: generate-build-version
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ inputs.semver }}
          token: ${{ secrets.PR_TOKEN }}

      - name: Build RC
        env:
          SEMVER: "7.609"
          BUILD_NUMBER: "3150"
          BITRISE_APP_ID: ${{ secrets.BITRISE_APP_ID }}
          BITRISE_BUILD_TRIGGER_TOKEN: ${{ secrets.BITRISE_BUILD_TRIGGER_TOKEN }}
          BITRISE_API_TOKEN: ${{ secrets.BITRISE_API_TOKEN }}
        run: ./scripts/rc-builds.sh
