##############################################################################################
#
# This Workflow is responsible for updating the latest build version of the project.
# You can provide your own base branch, tag, or SHA for git operations and the pull request.
# and it will generate the latest build version & update the neccessary files for you.
#
##############################################################################################
name: Update Latest Build Version

on:
  workflow_dispatch:
    inputs:
      base-branch:
        description: 'The base branch, tag, or SHA for git operations and the pull request.'
        required: true
jobs:
  generate-build-version:
    uses: MetaMask/metamask-mobile-build-version/.github/workflows/metamask-mobile-build-version.yml@v0.3.0
    permissions:
      id-token: write

  bump-version:
    runs-on: ubuntu-latest
    needs: generate-build-version
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ inputs.base-branch }}
          token: ${{ secrets.PR_TOKEN }}
      - id: bump-script
        uses: ./.github/actions/bump-build-version
        with:
          build-version: ${{ needs.generate-build-version.outputs.build-version }}
          ref: ${{ inputs.base-branch }}

