##############################################################################################
#
# This Workflow is responsible for updating the latest build version of the project.
# You can provide your own base branch, tag, or SHA for git operations and the pull request.
# and it will generate the latest build version & update the neccessary files for you.
#
##############################################################################################
name: Update Latest Build Version

on:
  workflow_dispatch:
    inputs:
      base-branch:
        description: 'The base branch, tag, or SHA for git operations and the pull request.'
        required: true
jobs:
  bump-version:
    uses: ./.github/workflows/bump-build-version.yml
    with:
      ref: ${{ inputs.base-branch }}
    permissions:
      id-token: write
      contents: write
